name = "MCWhores Mods"
author = "ryleu"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e465c9843b3d793a031ad74bffd31cb2ef84518c5959942272d65eb97ea7e5d"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
