name = "MCWhores Mods"
author = "ryleu"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "956e43eb9cc96154974b3b9d1240be1ea3d23e5dd8ced9eee2d05ce6c3cffaa8"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
