name = "MCWhores Mods"
author = "ryleu"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "efe82c5dab7e6758caee4f787a888346fea6d2a6c6a2d7b38ffb988aacadfa97"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
