name = "MCWhores Mods"
author = "ryleu"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0333706890aad33d8f9c4b71badbba68c843826f5d121f87a0efffff27ec9cd7"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
