name = "MCWhores Mods"
author = "ryleu"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6cc43d1818802bec8380991c11a522748a71b3f0159236d8cf95c8a2385e30ae"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
