name = "MCWhores Mods"
author = "ryleu"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d144e1d892a399e9e7fbd9fb1879adddddb2b529ccdd4e30d0811d303e226d0"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
