name = "MCWhores Mods"
author = "ryleu"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41483d5d5bcb306074a68f4344c4ae7ddf96267d4a68c35a6f00d619d8cf2cb3"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
