name = "MCWhores Mods"
author = "ryleu"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "466818446d89d2f78d3bce5570323b0bbe92e8e95e5e3fdae881d21fe0b871de"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
