name = "MCWhores Mods"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "85d7370c0005616474c5f0dbb99d3a9919eb28d7ad384189881dccb9c5ca3d2e"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
