name = "MCWhores Mods"
author = "ryleu"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c3e6d46be6bb54e155b8535b0d41c8a4fdbc1d44aca2c4b290e9ba530dcbf49"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
