name = "MCWhores Mods"
author = "ryleu"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d1ce27376696cec63e3d468c25301a46b0c0d44b648365864c96faceb93fd4e3"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
