name = "MCWhores Mods"
author = "ryleu"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "acdc9734fcc0b4b0447b3f6a2fef2384b035790141e8d10f4cecb4938c1346c4"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
