name = "MCWhores Mods"
author = "ryleu"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "08de0b25b6a1451b47e56ae24bf508164125965032642407658215b9af4078d8"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
