name = "MCWhores Mods"
author = "ryleu"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42098fee6347bb93528d0210f9afa79f685d45e8843241e0125b5ff1184e12e1"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
