name = "MCWhores Mods"
author = "ryleu"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd32c24583df4eda2fa1a6f735e2d8a844070d38063abfb9cf6f53c844289dbe"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
