name = "MCWhores Mods"
author = "ryleu"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8630e05fddc11432cf360db48ca1408bc551895d1c9574fe7040f91efcdd719e"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
