name = "MCWhores Mods"
author = "ryleu"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e23161ee7d6792fc236a0335430b23a61c352f3eb2c5cac963a1a6c8aa5522e8"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
