name = "MCWhores Mods"
author = "ryleu"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "191204bd2beb8cbb800c819e3a6ed0a41a1f201372eaaa561c8a6812195f6103"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
