name = "MCWhores Mods"
author = "ryleu"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "444fc6e19674c692f43b46073eea15bf4be679edba3c3df88bc2068fe1ebcd18"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
