name = "MCWhores Mods"
author = "ryleu"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd6af703e7ce2857885b6d60ca7ce08a6b579b98013a324b3aa18f270d9625a5"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
